# Generated by Django 3.2.15 on 2022-09-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_products_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('name',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
